# Creating Arrays

In [ ]:
print('Hello world !')

In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)                       #implementing a 1d array

[1 2 3 4 5]


In [6]:
print(np.__version__)            # checking the numpy version 

1.23.4


# Array Indexing

In [49]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [7]:
print(type(arr))                 # checking the type of array object (nd array)

<class 'numpy.ndarray'>


In [14]:
arr1 = np.array({1,2,3,4,5})     # array object as sets

In [15]:
print(arr1)

{1, 2, 3, 4, 5}


In [16]:
arr2 = np.array(42)              #implementing a 0d array object 

In [128]:
print(arr2)
print(type(arr2))

42
<class 'numpy.ndarray'>


In [46]:
arr3 = np.array([1,2,3,4,5])     #implementing a 1d array

In [48]:
print(arr3)
print(arr3[1])
print(arr3[1]+arr[3])                    # we can add the elements of an array like lists in python

[1 2 3 4 5]
2
6


In [49]:
print(arr4)

[[1 2 3]
 [4 5 6]]


In [53]:
print(arr4[0])
print(arr4[0,2])
print(arr4[1,2])             # array indexing

[1 2 3]
3
6


In [54]:
print(d3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [129]:
print(d3[0])            # array indexing

[[1 2 3]
 [4 5 6]]


In [56]:
print(d3[0,1])         # array indexing

[4 5 6]


In [57]:
print(d3[0,1,1])      # array indexing

5


In [60]:
print(d3[-1,0,0])     # array indexing

1


# Array Slicing

In [47]:
print(arr3[::2])

[1 3 5]


In [26]:
arr4 = np.array(((1,2,3),(4,5,6)))       #implementing a 2d array

In [28]:
print(arr4)

[[1 2 3]
 [4 5 6]]


In [38]:
d3 = np.array((((1,2,3),(4,5,6)),((1,2,3),(4,5,6))) )          #implementing a 3d array

In [39]:
print(d3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [40]:
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print(d3.ndim)                     # using (array.ndim) we can find the array of a dimension 


0
1
2
3


In [43]:
d5 = np.array([1,2,3,4], ndmin=5)      # we can explicitly define the dimension of an array using the argument ndmin - ndmin = 5

In [44]:
print(d5)

[[[[[1 2 3 4]]]]]


In [45]:
print(d5.ndim)

5


In [85]:
print(arr3[::1])      # array slicing

[1 2 3 4 5]


In [97]:
print(arr4[0:2,0:1])        # array slicing

[[1]
 [4]]


In [98]:
arr = np.array(['apple', 'banana', 'cherry'])

# Data type

In [101]:
print(arr.dtype)          # we can find the data type of an array using dtype property - (array.dtype)

<U6


In [104]:
print(arr4.dtype)

int32


In [109]:
arr3 = np.array([1,2,3,4,5],dtype = 'i')         # we can explicitly assign datatype using an optional argument, dtype = 'datatype'

In [110]:
print(arr3.dtype)                     

int32


In [117]:
arr = np.array([1.1,2.2,3.3])

newarr = arr.astype('i')                 # we can convert an array datatype by creating a copy of the array and convert it into another datatype.

In [130]:
print(newarr)

[1 2 3]


In [131]:
print(newarr.dtype)

int32


In [132]:
newarr2 = arr.astype('int')     # converting it into int datatype from float

In [133]:
print(newarr2.dtype)

int32


In [134]:
newarr3 = arr.astype('bool')       # converting it into bool datatype from float

In [135]:
print(newarr3.dtype)

bool


# Copy vs View

In [9]:
import numpy as np

ar1 = np.array([1,2,3,4,5])
x=ar1.copy()
x[0] = 42

print(x)
print(ar1)                                      #  copying the array and changes, doesn't affects the original data

[42  2  3  4  5]
[1 2 3 4 5]


In [5]:
ar1 = np.array([1,2,3,4,5])
y=ar1.view()
ar1[0] = 42

print(y)
print(ar1)                                    # make a view of the original data

[42  2  3  4  5]
[42  2  3  4  5]


In [10]:
ar1 = np.array([1,2,3,4,5])
y=ar1.view()
y[0] = 9

print(y)
print(ar1)                                   #  viewing the array and changes, affects the original data 

[9 2 3 4 5]
[9 2 3 4 5]


In [11]:
print(x.base)
print(y.base)                                # copy returns "none" but view returns the original array which is the base source of data

None
[9 2 3 4 5]


# Array shape and reshape

In [13]:
arr4 = np.array(((1,2,3),(4,5,6)))  
print(arr4.shape)

(2, 3)


In [15]:
d5 = np.array([1,2,3,4,5], ndmin = 5)
print(d5.shape)

(1, 1, 1, 1, 5)


In [16]:
d3 = np.array((((1,2,3),(4,5,6)),((1,2,3),(4,5,6))), ndmin = 4 )
print(d3.shape)

(1, 2, 2, 3)


In [19]:
arr5 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr5 = arr5.reshape(4,3)
newarr6 = arr5.reshape(2,3,2)
print(newarr5)
print(newarr6)                                  # we can able to reshape an array in form of only feasible format only like (a*b....*n)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
print(newarr6.base)                           # it is returning the original array, so it is just a view not a "copy"

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)                                '''You are allowed to have one "unknown" dimension. Pass -1 as the value, 
                                               and NumPy will calculate this number for you.
                                               *We can not pass -1 to more than one dimension.'''

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
arr0 = np.array([[1, 2, 3], [4, 5, 6]])

newarr0 = arr0.reshape(-1)

print(newarr0)                           

[1 2 3 4 5 6]


# Array Iterating

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

for i in arr:
    print(i)                                          #Iterating through 1-d array

1
2
3
4
5


In [3]:
arr2 = np.array(([1,2,3],[4,5,6]))

for i in arr2:
    print(i)                              #Iterating through 2-d array

[1 2 3]
[4 5 6]


In [4]:
for i in arr2:
    for j in i:
        print(j)

1
2
3
4
5
6


In [14]:
arr3 = np.array((([1,2,3],[4,5,6]),([7,8,9],[10,11,12])))

In [15]:
for i in arr3:
    for j in i:
        for k in j:
            print(k)                #Iterating through 3-d array

1
2
3
4
5
6
7
8
9
10
11
12


In [18]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3 = np.array((([1,2,3],[4,5,6]),([7,8,9],[10,11,12])))


for x in np.nditer(arr3):
  print(x)                                          #The np.nditer() function will help us to replace the 'n' for loops usage.

1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)                                                                                     
                                 #use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
             '''NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to 
                perform this action, that extra space is called buffer, 
                and in order to enable it in nditer() we pass flags=['buffered'].'''

b'1'
b'2'
b'3'


In [21]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)                                       #iterating through different step size

1
3
5
7


In [22]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)                            # giving enumeration to each array elements

(0,) 1
(1,) 2
(2,) 3


In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)                           # giving enumeration to a 2-d array to each elements

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [25]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))              # joining arrays using axis = 0

print(arr)

[1 2 3 4 5 6]


In [37]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)           # joining arrays using axis =1

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [39]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)               # Joining Arrays Using Stack Functions


print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Array Join

In [41]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))               # Joining Arrays Using "hstack" Functions - to stack along rows


print(arr)

[1 2 3 4 5 6]


In [44]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))               # Joining Arrays Using "hstack" Functions - to stack along columns (default one)


print(arr)

[[1 2 3]
 [4 5 6]]


In [45]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))               # Joining Arrays Using "hstack" Functions - to stack along height (depth)


print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Array Splitting

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6,7])

newarr = np.array_split(arr, 3)

print(newarr)                                # array_split() will split accordingly even though there is shortage of elements.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
    arr1 = np.array([1,2,3,4,5,6])

newarr2 = np.split(arr1,3)

print(newarr2)                             # split() function will throw an error when there is shortage of elements

[array([1, 2]), array([3, 4]), array([5, 6])]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])                              # accessing the arrays

[1 2]
[3 4]
[5 6]


In [7]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)                                 # splitting 2-d arrays

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 2)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.dsplit(arr, 5)

print(newarr)

ValueError: dsplit only works on arrays of 3 or more dimensions

# Array Search

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [54]:
    arr = np.array([6,2,11,3,7, 8, 9,1])

x = np.searchsorted(arr, 7)

print(x)                                      # using search sorted it returens the index, where the 7 should be inserted

2


In [55]:
arr = np.array([6,7,1,3,5,8,10,15])

x = np.searchsorted(arr, 7, side='right')
    
print(x)                            # By default left most index is returned, but if we give side='right', it will give right most index instead

5


In [53]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# Sorting Arrays

In [56]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [57]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [58]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [59]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtering Arrays

In [60]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [61]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [63]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
