<a href="https://colab.research.google.com/github/azhagan2/Numpy/blob/main/uFunc_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3,4])
y = np.array([5,2,7,8])

z = np.add(x,y)
print(z)

[ 6  4 10 12]


In [ ]:
def add(x,y):
  return x+y

myadd = np.frompyfunc(add,2,1)

print(myadd(x,y))

[6 4 10 12]


In [ ]:
print(type(np.add))
print(type(np.concatenate))

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [ ]:
if (type(np.add) == np.ufunc):
  print('add is ufunc')
else:
  print('Not ufunc')

add is ufunc


In [ ]:
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.power(x,y))
print(np.mod(x,y))
print(np.remainder(x,y))
print(np.divmod(x,y))
print(np.absolute([-4,-32,-56,90]))

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]
[  1   4  27 256]
[0 0 0 0]
[0 0 0 0]
(array([1, 1, 1, 1]), array([0, 0, 0, 0]))
[ 4 32 56 90]


In [ ]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [ ]:
arr = np.fix([-3.1666, 3.999])
print(arr)

[-3.  3.]


In [ ]:
arr = np.around([-3.1666, 3.56],1)
print(arr)

[-3.2  3.6]


In [ ]:
arr = np.ceil([-4.9666, 3.999])
print(arr)

[-4.  4.]


In [ ]:
arr = np.floor([-3.1666, 3.999])
print(arr)

[-4.  3.]


In [ ]:
arr = np.arange(1, 11)
print(arr)
print(np.log2(arr))

[ 1  2  3  4  5  6  7  8  9 10]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]


In [ ]:
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]


In [ ]:
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [ ]:
from math import log
nplog = np.frompyfunc(log, 2, 1)

print(nplog(100,15))


1.7005483074552052


In [ ]:
arr=np.array([1,2,3,4])
arr1=np.array([5,6,7,8])

print(np.add(arr,arr1))

[ 6  8 10 12]


In [ ]:
print(np.sum([arr,arr1]))

36


In [ ]:
print(np.sum([arr,arr1],axis=0))

[ 6  8 10 12]


In [ ]:
print(np.sum([arr,arr1],axis=1))

[10 26]


In [ ]:
a=(np.cumsum(arr))
b=(np.cumsum(arr1))
z=a+b
print(z,a,b)

[ 6 14 24 36] [ 1  3  6 10] [ 5 11 18 26]


In [ ]:
print(np.prod(arr1))

1680


In [ ]:
print(np.prod(arr))

24


In [ ]:
print(np.prod([arr,arr1]))

40320


In [ ]:
print(np.prod([arr,arr1],axis=0))

[ 5 12 21 32]


In [ ]:
print(np.cumprod(arr1))

[   5   30  210 1680]


In [ ]:
print(np.diff(arr))

[1 1 1]


In [ ]:
x=np.array([55,34,90,87])
x=print(np.diff(x,n=2))

[ 77 -59]


In [ ]:
y=np.array([1,2,3,4])
a=4
b=9
print(np.lcm(a,b))

36


In [ ]:
print(np.l)

In [1]:
import numpy as np

In [2]:
print(np.sin(np.pi/2))

1.0


In [9]:
arr=np.array([np.pi/2, np.pi/3, np.pi/4, np.pi])
print(np.sin(arr))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 1.22464680e-16]


In [5]:
arr1=np.array([0,90,270,360])
print(np.deg2rad(arr1))

[0.         1.57079633 4.71238898 6.28318531]


In [10]:
print(np.rad2deg(arr))

[ 90.  60.  45. 180.]


In [11]:
print(np.arcsin(1.0))

1.5707963267948966


In [15]:
print(np.arcsin([1,-1,0.4]))

[ 1.57079633 -1.57079633  0.41151685]


In [18]:
print(np.hypot(10,6))

11.661903789690601


In [19]:
print(np.sinh(np.pi/2))

2.3012989023072947


In [20]:
print(np.sinh(arr))

[ 2.3012989   1.24936705  0.86867096 11.54873936]


In [21]:
print(np.sinh(arr1))

[0.00000000e+000 6.10201647e+038 9.08824693e+116 1.10913265e+156]


In [22]:
arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]


In [33]:
set1=np.array([1,1,1,1,2,3,2,3,4,5,4,4,5,7,8,4,11])

print(np.unique(set1))

[ 1  2  3  4  5  7  8 11]


In [24]:
set2=np.array([1,2,5,3,4,7,1,6,8,9,10,4,7])

print(np.union1d(set1, set2))

[ 1  2  3  4  5  6  7  8  9 10]


In [27]:
print(np.intersect1d(set1,set2, assume_unique=True))

[1 1 1 1 1 2 2 3 3 4 4 4 4 4 5 5 7 7 8]


In [35]:
print(np.setdiff1d(set1, set2,assume_unique=True))

[11]


In [36]:
print(np.setxor1d(set1, set2,assume_unique=True))

[ 6  9 10 11]
