<a href="https://colab.research.google.com/github/azhagan2/Numpy/blob/main/uFunc_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
x = np.array([1,2,3,4])
y = np.array([5,2,7,8])

z = np.add(x,y)
print(z)

[ 6  4 10 12]


In [12]:
def add(x,y):
  return x+y

myadd = np.frompyfunc(add,2,1)

print(myadd(x,y))

[6 4 10 12]


In [ ]:
print(type(np.add))
print(type(np.concatenate))

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [ ]:
if (type(np.add) == np.ufunc):
  print('add is ufunc')
else:
  print('Not ufunc')

add is ufunc


In [ ]:
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.power(x,y))
print(np.mod(x,y))
print(np.remainder(x,y))
print(np.divmod(x,y))
print(np.absolute([-4,-32,-56,90]))

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]
[  1   4  27 256]
[0 0 0 0]
[0 0 0 0]
(array([1, 1, 1, 1]), array([0, 0, 0, 0]))
[ 4 32 56 90]


In [ ]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [ ]:
arr = np.fix([-3.1666, 3.999])
print(arr)

[-3.  3.]


In [ ]:
arr = np.around([-3.1666, 3.56],1)
print(arr)

[-3.2  3.6]


In [ ]:
arr = np.ceil([-4.9666, 3.999])
print(arr)

[-4.  4.]


In [ ]:
arr = np.floor([-3.1666, 3.999])
print(arr)

[-4.  3.]


In [6]:
arr = np.arange(1, 11)
print(arr)
print(np.log2(arr))

[ 1  2  3  4  5  6  7  8  9 10]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]


In [7]:
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]


In [8]:
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [14]:
from math import log
nplog = np.frompyfunc(log, 2, 1)

print(nplog(100,15))


1.7005483074552052


In [21]:
arr=np.array([1,2,3,4])
arr1=np.array([5,6,7,8])

print(np.add(arr,arr1))

[ 6  8 10 12]


In [35]:
print(np.sum([arr,arr1]))

36


In [26]:
print(np.sum([arr,arr1],axis=0))

[ 6  8 10 12]


In [27]:
print(np.sum([arr,arr1],axis=1))

[10 26]


In [33]:
a=(np.cumsum(arr))
b=(np.cumsum(arr1))
z=a+b
print(z,a,b)

[ 6 14 24 36] [ 1  3  6 10] [ 5 11 18 26]


In [37]:
print(np.prod(arr1))

1680


In [38]:
print(np.prod(arr))

24


In [41]:
print(np.prod([arr,arr1]))

40320


In [44]:
print(np.prod([arr,arr1],axis=0))

[ 5 12 21 32]


In [46]:
print(np.cumprod(arr1))

[   5   30  210 1680]


In [47]:
print(np.diff(arr))

[1 1 1]


In [51]:
x=np.array([55,34,90,87])
x=print(np.diff(x,n=2))

[ 77 -59]


In [52]:
y=np.array([1,2,3,4])
a=4
b=9
print(np.lcm(a,b))

36


In [55]:
print(np.lcm.reduce(y))

12


In [56]:
y=np.arange(1,11)

print(np.lcm.reduce(y))

2520


In [57]:
print(np.gcd(a,b))

1


In [59]:
print(np.gcd.reduce([20, 8, 32, 36, 16]))

4
